### RUTAS APIS DIVISION
@api = http://localhost:3000/aulas

### LISTAR
GET {{api}}/get

### CREAR
POST {{api}}/create
Content-Type: application/json

{
    "nombre":"103",
    "descripcion": "Laboratorio",
    "idEdificio": 1
}

### LISTAR POR ID
GET {{api}}/getbid/15

### ELIMINAR POR ID
DELETE {{api}}/delete/3


### EDITAR POR ID
PUT {{api}}/update/15
Content-Type: application/json

{
    "nombre":"109",
    "descripcion": "Laboratorio",
    "idEdificio": 1
}