### RUTAS APIS DIVISION
@api = http://localhost:3000/division

### LISTAR
GET {{api}}/get

### CREAR
POST {{api}}/create
Content-Type: application/json

{
    "nombre":"Gastronomía",
    "descripcion": "Departamento de Gastronomía"
}

### LISTAR POR ID
GET {{api}}/getbid/3

### ELIMINAR POR ID
DELETE {{api}}/delete/2


### EDITAR POR ID
PUT {{api}}/update/1
Content-Type: application/json

{
    "nombre": "Tecnologías de la Información y Comunicación",
    "descripcion": "Departamento de Ti"
}