### RUTAS APIS DIVISION
@api = http://localhost:3000/edificio

### LISTAR
GET {{api}}/get

### CREAR
POST {{api}}/create
Content-Type: application/json

{
    "nombre": "D4",
    "descripcion": "Edificon de Mecatrónica",
    "idDivision": 2
}

### LISTAR POR ID
GET {{api}}/getbid/3

### ELIMINAR POR ID
DELETE {{api}}/delete/3


### EDITAR POR ID
PUT {{api}}/update/2
Content-Type: application/json

{
    "nombre": "D4",
    "descripcion": "Edificon de Mecatrónica",
    "idDivision": 2
}