### RUTAS APIS DIVISION
@api = http://localhost:3000/grupo

### LISTAR
GET {{api}}/get

### CREAR
POST {{api}}/create
Content-Type: application/json

{
      "nombre": "Z",
      "cuatrimestre": 7,
      "turno": "Matutino",
      "idPeriodo": 1,
      "idAula": 14,
      "idTutor": 665,
      "idEspecialidad": 1
}

### LISTAR POR ID
GET {{api}}/getbid/5

### ELIMINAR POR ID
DELETE {{api}}/delete/6


### EDITAR POR ID
PUT {{api}}/update/5
Content-Type: application/json

{
      "nombre": "h",
      "cuatrimestre": 4,
      "turno": "Vespertino",
      "idPeriodo": 1,
      "idAula": 1,
      "idTutor": 3,
      "idEspecialidad": 3
}